version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://localhost:29092
    ports:
      - "29092:29092"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example  
      POSTGRES_USER: exampleuser 
      POSTGRES_DB: exampledb 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

volumes:
  mongodb_data:
