-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.test
(
    id integer NOT NULL,
    name character(1) COLLATE pg_catalog."default",
    address character(1) COLLATE pg_catalog."default",
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id integer,
    name text
);
END;